### ISSUE TITLE
Rebuild gstreamer since the glib-2.58 pin advancement

### ISSUE THREAD

**Issue by croth1** [conda-forge/gstreamer-feedstock#23]
The gstreamer-feedstock has diverged from its pin. Unfortunately, we need to rebuild it due to the recent glib pin advancement. (Version 1.12 is pinned on linux).

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - cairo=1.16
  - qt==5.6.2=hbe13537_1012 -> gstreamer[version='>=1.12.5,<1.13.0a0'] -> glib[version='>=2.56.2,<2.57.0a0']
```

Do you think it's better to rerender 1.12, or should we advance the pin?

**Comment by croth1** [comment]
@conda-forge/gstreamer  @conda-forge/core can somebody help me find the right way to solve this issue?

**Comment by scopatz** [comment]
It is probably better to update the pins
