### ISSUE TITLE
Begin using meson build system

### ISSUE THREAD

**Issue by joshdoe** [conda-forge/gstreamer-feedstock#41]
Currently GStreamer 1.16 is being built, which supports both meson and automake, however in master and for the next 1.18 release, automake has been removed completely in support of meson. Some feedstock that have moved to meson include [atk](https://github.com/conda-forge/atk-feedstock) and [gdk-pixbuf](https://github.com/conda-forge/gdk-pixbuf-feedstock).

I'll take a stab at doing this, and submit a PR if successful

**Comment by tjwilli58** [comment]
@joshdoe , You probably saw this already, but [gobject-introspection-feedstock ](https://github.com/conda-forge/gobject-introspection-feedstock) has a recipe that uses meson.

**Comment by tjwilli58** [comment]
I just went to [atk-feedstock](https://github.com/conda-forge/atk-feedstock) and saw that recipe uses meson too. 
Never mind.

**Comment by tjwilli58** [comment]
What's the status of this?

**Comment by joshdoe** [comment]
I was working to use gst-build as a first attempt, and there are a bunch of meson bugs on Windows that are being worked on. Once it works well there, then I was going to revisit this. However I'm trying to port to meson plus Windows at the same time, should probably just do it on Linux first.
