### ISSUE TITLE
error when updating

### ISSUE THREAD

**Issue by chapochn** [conda-forge/gstreamer-feedstock#48]
when I upload some packages
`conda update -c conda-forge mne`
I get this error:

InvalidArchiveError("Error with archive /home/nmc/Programs/anaconda3/pkgs/gstreamer-1.18.2-ha23517c_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nFailed to create dir 'share/gdb/auto-load/home/conda/feedstock_root/build_artifacts/gstreamer_and_plugins_1607343170771/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold'")

`conda list`
packages in environment at /home/nmc/Programs/anaconda3/envs/mne:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
apptools                  4.5.0                      py_0    conda-forge
blosc                     1.20.0               he1b5a44_0    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cftime                    1.2.1            py38h8790de6_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
curl                      7.71.1               he644dc0_5    conda-forge
cvxopt                    1.2.5            py38hf48cded_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
dipy                      1.1.0            py38hc1659b7_1    conda-forge
dsdp                      5.8               h23d7751_1203    conda-forge
envisage                  4.9.2                      py_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1111    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
glpk                      4.65              he80fd80_1002    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py38hfb01d0b_104    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
hdf5storage               0.1.15                     py_1    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsoncpp                   1.8.4             hc9558a2_1002    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  10.0.1          default_hde54327_1    conda-forge
libcurl                   7.71.1               hcdd3856_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
libgomp                   9.3.0               h24d8f2e_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnetcdf                 4.7.4           nompi_h84807e1_105    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     12.3                 h5513abc_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
llvmlite                  0.34.0           py38h4f45e52_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
matplotlib-base           3.3.1            py38h91b0d89_1    conda-forge
mayavi                    4.7.2            py38hda7c5db_0    conda-forge
meshio                    4.1.1                      py_0    conda-forge
metis                     5.1.0             he1b5a44_1006    conda-forge
mne                       0.20.8           py38h32f6830_0    conda-forge
mock                      4.0.2            py38h32f6830_0    conda-forge
mysql-common              8.0.21                        0    conda-forge
mysql-libs                8.0.21               hf3661c5_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
netcdf4                   1.5.4           nompi_py38hec8b9af_102    conda-forge
nibabel                   3.1.1                      py_0    conda-forge
nilearn                   0.6.2              pyh5ca1d4c_0    conda-forge
nspr                      4.28                 he1b5a44_0    conda-forge
nss                       3.56                 he751ad9_0    conda-forge
numba                     0.51.2           py38hc5bc63f_0    conda-forge
numexpr                   2.7.1            py38hcb8c335_1    conda-forge
numpy                     1.19.1           py38hbc27379_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.1            py38h950e882_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    7.2.0            py38h9776b28_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
psutil                    5.7.2            py38h1e0a361_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pydicom                   2.0.0              pyh9f0ad1d_0    conda-forge
pyface                    7.0.0              pyh9f0ad1d_1    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38ha8c2ead_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysurfer                  0.11.0                     py_0    conda-forge
pytables                  3.6.1            py38h1b207d3_2    conda-forge
python                    3.8.5           h1103e12_7_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-picard             0.4                pyh5ca1d4c_1    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyvista                   0.25.3                     py_0    conda-forge
qt                        5.12.9               h1f2b2cb_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scikit-learn              0.23.2           py38hee58b96_0    conda-forge
scipy                     1.5.2            py38h8c5af15_0    conda-forge
scooby                    0.5.6              pyh9f0ad1d_0    conda-forge
setuptools                49.6.0           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_0    conda-forge
statsmodels               0.12.0           py38h1e0a361_0    conda-forge
suitesparse               5.7.2                h717dc36_0    conda-forge
tbb                       2020.2               hc9558a2_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
traits                    6.1.0            py38h1e0a361_0    conda-forge
traitsui                  7.0.1              pyh9f0ad1d_0    conda-forge
vtk                       8.2.0           py38hf2e56f5_218    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

`conda info`
     active environment : mne
    active env location : /home/nmc/Programs/anaconda3/envs/mne
            shell level : 2
       user config file : /home/nmc/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/nmc/Programs/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/nmc/Programs/anaconda3/pkgs
                          /home/nmc/.conda/pkgs
       envs directories : /home/nmc/Programs/anaconda3/envs
                          /home/nmc/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.3 Linux/5.4.0-58-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False

Was not sure where to report this. Thank you for your help and let me know what additional detail you need.

**Comment by tito** [comment]
Yep, same issue here, the archive have build artifacts inside that make it uninstallable on encrypted/mounted directory:

share/gdb/auto-load/home/conda/feedstock_root/build_artifacts/gstreamer_and_plugins_1607343170771/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/__pycache__/libgstreamer-1.0.so.0.1802.0-gdb.cpython-39.pyc

This should not be in the archive

**Comment by tschoonj** [comment]
Thanks for reporting this issue. #49 should fix it.
